trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

steps:
- script: |
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    pip install pytest
  displayName: 'Install dependencies'

- script: |
    pytest -v -s test_grafana.py
  displayName: 'Run UI tests'